### ISSUE TITLE
[S1-PBI4] Shopping Cart

### ISSUE THREAD

**Issue by auliyanurpratama** [SI-RPL-2023/SI4407_262_FarmBox#4]
Sistem mampu memungkinkan user untuk dapat menambahkan produk yang ingin dibeli ke dalam shopping cart atau keranjang belanja

**Comment by HfzRka21** [comment]
[Shopping Cart.pdf](https://github.com/SI-RPL-2023/SI4407_262_FarmBox/files/11828628/Shopping.Cart.pdf)
