### ISSUE TITLE
[S1-PBI6] Jual Produk Page

### ISSUE THREAD

**Issue by auliyanurpratama** [SI-RPL-2023/SI4407_262_FarmBox#6]
Sistem mampu menampilkan halaman penjualan produk dan mengunggah produk yang ingin dijual ke dalam website

**Comment by HfzRka21** [comment]
[Menjual Produk.pdf](https://github.com/SI-RPL-2023/SI4407_262_FarmBox/files/11828635/Menjual.Produk.pdf)
