### ISSUE TITLE
[S2-PBI2] Wishlist

### ISSUE THREAD

**Issue by daffaalhanif** [SI-RPL-2023/SI4407_262_FarmBox#8]
Sistem mampu memungkinkan user untuk menambahkan produk ke dalam wishlist lalu menampilkan halaman berisi wishlist

**Comment by HfzRka21** [comment]
[Wishlist.pdf](https://github.com/SI-RPL-2023/SI4407_262_FarmBox/files/11828649/Wishlist.pdf)
